#!/usr/bin/env bash
#creating a loop that prints numbers from 1-100 with conditions to it
count=1
until [ $count -gt 100 ] 
do 
	if ((count % 5 == 0))&& ((count % 3 == 0));then
		echo "FizzBuzz"
	elif  ((count%5==0)) ;then
		echo "Buzz"
	elif  ((count%3==0)) ;then
		echo "Fizz"
	else
		echo "$count"
	fi
	((count+=1))
done
