#!/usr/bin/env bash
#using while loop combined with if elif else command to loop 1 -10 with rules
count=0
while [ $count -lt 10 ]
do
	((count+=1))
	if [ $count -eq 4 ];then
		echo "bad luck"
	elif [ $count -eq 8 ];then
		echo "good luck"
	else
		echo "Best School"
	fi
	
done
