#!/usr/bin/env bash
#using if to check details of a file
if [ -e "school" ];then
	if [ -s "school" ];then
		if [ -f "school" ];then
			echo "school file exists"
			echo "school file is not empty"
			echo "school is a regular file"
		else
			echo "school file exists"
			echo "school file is not empty"
		fi
	else
		echo "school file exists"
		echo "school file is empty"
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
