#!/usr/bin/env bash
#script creates fil containing its pid and messags when trying to execute sigkill and sigint siganl

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; sudo rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT

while true
do
    echo "To infinity and beyond"
done
